### ISSUE TITLE
Está finalizado? Posso fazer fork sem medo?

### ISSUE THREAD

**Issue by diegovilarinho** [iget-master/cielo-checkout#3]
Está finalizado? Posso fazer fork sem medo?

**Comment by iget-master** [comment]
@diegovilarinho esse pacote está operando em um serviço nosso, porém não está 100% finalizado, talvez necessite ajustes.

**Comment by quinhone** [comment]
teria uma docs pra ajudar no uso dele?

**Comment by iget-master** [comment]
@quinhone Infelizmente não. Por sorte, estamos trabalhando neste pacote para utilizar num novo projeto. Se der tempo, faço um README com algumas informações de como utilizar.
